ALTER ROLLBACK SEGMENT "RBS0" 
    STORAGE ( MAXEXTENTS UNLIMITED) ; 
ALTER ROLLBACK SEGMENT "RBS1" 
    STORAGE ( MAXEXTENTS UNLIMITED) ; 
ALTER ROLLBACK SEGMENT "RBS2" 
    STORAGE ( MAXEXTENTS UNLIMITED) ; 
ALTER ROLLBACK SEGMENT "RBS3" 
    STORAGE ( MAXEXTENTS UNLIMITED) ; 
ALTER ROLLBACK SEGMENT "RBS4" 
    STORAGE ( MAXEXTENTS UNLIMITED) ; 
ALTER ROLLBACK SEGMENT "RBS5" 
    STORAGE ( MAXEXTENTS UNLIMITED) ; 
ALTER ROLLBACK SEGMENT "RBS6" 
    STORAGE ( MAXEXTENTS UNLIMITED) ; 
COMMIT;

