CREATE PROCEDURE SP_INSERENOLOCK
AS
  DECLARE @CODCOLIGADA DCODCOLIGADA
  DECLARE @CODSENTENCA VARCHAR(16)
  DECLARE @SENTENCA VARCHAR(8000)
  DECLARE @SENTENCA_ALTERADA VARCHAR(255)
  DECLARE @SENTENCA_ALTERAR VARCHAR(255)
  DECLARE @STATUS INT
  DECLARE @COMANDO VARCHAR(255)
  
  DECLARE CR_SENTENCASQL CURSOR FOR
    SELECT CODCOLIGADA, CODSENTENCA, CAST(SENTENCA AS VARCHAR(8000))
    FROM GCONSSQL (NOLOCK)
  
  OPEN CR_SENTENCASQL
  
  FETCH NEXT FROM CR_SENTENCASQL INTO @CODCOLIGADA, @CODSENTENCA, @SENTENCA
  
  SET NOCOUNT ON -- DESABILITA CONTADOR DE RESULTADOS
  
  SET @STATUS = 0 -- STATUS DA ALTERACAO (0 - NÃO ALTERADO / 1 - ALTERADO)
  
  -- CRIA TABELA DE BACKUP/ALTERAÇÃO
  IF EXISTS (SELECT * 
             FROM SYSOBJECTS
             WHERE XTYPE = 'U'
             AND NAME = 'ZGCONSSQL')
    DROP TABLE ZGCONSSQL
  
  SELECT * INTO ZGCONSSQL
  FROM GCONSSQL
  
  ALTER TABLE ZGCONSSQL ADD STATUS INT
  
  ALTER TABLE ZGCONSSQL ALTER COLUMN SENTENCA VARCHAR(8000)
  
  UPDATE ZGCONSSQL SET STATUS = 0
  
  -- INICIA BLOCO DE REPETIÇÃO E VALIDAÇÃO DAS CONSULTAS SQL
  WHILE (@@FETCH_STATUS = 0)
  BEGIN
    PRINT '----------------------------------------------------------'
    PRINT '- COLIGADA   : '+CAST(@CODCOLIGADA AS VARCHAR)
    PRINT '- CODSENTENCA: '+@CODSENTENCA
  
    -- ARMAZENA PEDACO DA STRING A SER ALTERADO (WHERE)
    SET @SENTENCA_ALTERAR =  REPLACE((SELECT
                                        SUBSTRING(
                                           (SUBSTRING(SENTENCA,(CHARINDEX('FROM',SENTENCA)+4), 
                                                                CHARINDEX('WHERE',SENTENCA))),
                                           1, 
                                           PATINDEX('%WHERE%',(SUBSTRING(SENTENCA,(CHARINDEX('FROM',SENTENCA)+4), 
                                                                                   CHARINDEX('WHERE',SENTENCA)))))
                                       FROM GCONSSQL
                                       WHERE CODCOLIGADA = @CODCOLIGADA
                                       AND CODSENTENCA = @CODSENTENCA),'W','')
    
    -- ALTERA EM VARIÁVEL O PEDACO DA STRING  
    SET @SENTENCA_ALTERADA = CASE ISNULL(PATINDEX('%,%',@SENTENCA_ALTERAR),0)
                               WHEN 0 THEN @SENTENCA_ALTERAR+'(NOLOCK) '
                               ELSE REPLACE((REPLACE(@SENTENCA_ALTERAR,'W','')),',',' (NOLOCK), ')+'(NOLOCK) '
                             END

    -- REALIZA TROCA DE COMANDOS
    IF LEN(ISNULL(@SENTENCA_ALTERAR,0)) > 1
    BEGIN
      UPDATE ZGCONSSQL SET SENTENCA = REPLACE(SENTENCA, @SENTENCA_ALTERAR, @SENTENCA_ALTERADA)
      WHERE CODCOLIGADA = @CODCOLIGADA
      AND CODSENTENCA = @CODSENTENCA
  
      SET @STATUS = 1
  
      UPDATE ZGCONSSQL SET STATUS = @STATUS
      WHERE CODCOLIGADA = @CODCOLIGADA
      AND CODSENTENCA = @CODSENTENCA
    END
   
    PRINT '- DE         : '+ISNULL(@SENTENCA_ALTERAR,'NULL')
    PRINT '- PARA       : '+ISNULL(@SENTENCA_ALTERADA,'NULL')
    PRINT '- STATUS     : '+CASE @STATUS
                              WHEN 0 THEN 'NÃO ALTERADO'
                              ELSE 'ALTERADO '
                            END
    PRINT '----------------------------------------------------------' 
    SET @SENTENCA_ALTERAR = NULL
    SET @SENTENCA_ALTERADA = NULL
    SET @STATUS = 0
    FETCH NEXT FROM CR_SENTENCASQL INTO @CODCOLIGADA, @CODSENTENCA, @SENTENCA
  END
  CLOSE CR_SENTENCASQL
  DEALLOCATE CR_SENTENCASQL
GO