  /*********************************************************/
  /* CLIENTE                  :VALDAC MODAS                */
  /* BANCO DE DADOS           :MSSQL                       */
  /* VERSÃO DO BANCO DE DADOS :2000                        */
  /* VERSÃO DA BASE DE DADOS  :4.02                        */
  /* DATA DE CRIAÇÃO          :25/06/2002                  */
  /* ANALISTA RESPONSÁVEL     :FUMIO                       */
  /* OCORRÊNCIA RMAGILIS      :212901                      */
  /* OBJETIVO:                :MANIPULAÇÃO DOS CAMPOS      */
  /*                           COMPLEMENTARES DO TIPO      */
  /*                           PAI E MÃE COMO ESTAVAM      */ 
  /*                           NO RMFOLHA PARA OS CAMPOS   */ 
  /*                           CORRESPONDENTES NO RMLABORE */
  /*********************************************************/

/* 1.0 - SCRIPT VALDAC */

PRINT '---- **** 1.0 - SCRIPT VALDAC **** ----'
GO

/* 1.1 - CRIAÇÃO E INSERÇÃO DAS TABELAS TEMPORÁRIAS */

PRINT '---- **** 1.1 - CRIAÇÃO E INSERÇÃO DAS TABELAS TEMPORÁRIAS **** ----'
GO

      /*
         TABELA PFDEPEND = ZFDEPEND
         TABELA PFCOMPL  = ZFCOMPL
         TABELA GDEFCOMPL= ZDEFCOMPL
      */      

      /* 
         A CRIAÇÃO DAS TABELAS ZFCOMPL E ZDEFCOMPL, SÃO EXATAMENTE
         COM OS MESMOS CAMPOS E ESTRUTURA DEFINIDA NA BASE DA VALDAC MODAS
         VISTO QUE ESTAS TABELAS VARIAM CONFORME O USO DO CLIENTE
      */

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE XTYPE='U' AND NAME='ZFDEPEND')
  DROP TABLE ZFDEPEND
GO


CREATE TABLE ZFDEPEND (
	CODCOLIGADA DCODCOLIGADA,
	CHAPA DCHAPA,
	NRODEPEND SMALLINT NOT NULL,
	NOME VARCHAR(45),
	CPF VARCHAR(12),
	DTNASCIMENTO DATETIME,
	SEXO VARCHAR(1),
	ESTADOCIVIL VARCHAR(1),
	LOCALNASCIMENTO VARCHAR(32),
	CARTORIO VARCHAR(40),
	NROREGISTRO VARCHAR(10),
	NROLIVRO VARCHAR(6),
	NROFOLHA VARCHAR(5),
	INCIRRF SMALLINT,
	INCINSS SMALLINT,
	INCASSISTMEDICA SMALLINT,
	INCPENSAO SMALLINT,
	INCDEFINIVEIS VARCHAR(20),
	GRAUPARENTESCO CHAR(1),
	CARTAOVACINA SMALLINT DEFAULT 0,
	PERCENTUAL RMDVALOR2,
	TIPOPENSAO SMALLINT,
	BANCO VARCHAR(3),
	AGENCIA VARCHAR(6),
	CONTACORRENTE VARCHAR(15),
	RESPONSAVEL VARCHAR(45),
	APLICACAO VARCHAR(1),
	FORCALCULO VARCHAR(8),
	BRUTO DLOGICONULL,
	DATAENTREGACERTIDAO DATETIME,
	FREQESCOLAR DLOGICONULL,
	UNIVERSITARIO DLOGICONULL,
	INCSALFAM DLOGICONULL,
	OBSERVACAO VARCHAR(80),
	FORMPENSAO VARCHAR(8))
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE XTYPE='U' AND NAME='ZDEFCOMPL')
  DROP TABLE ZDEFCOMPL
GO

CREATE TABLE ZDEFCOMPL (
	CODCOLIGADA DCODCOLIGADA,
	APLICACAO VARCHAR(1) NOT NULL,
	TABDADOS VARCHAR(22) NOT NULL,
	NOMECOLUNA VARCHAR(20) NOT NULL,
	DESCRICAO VARCHAR(40),
	CODTABDINAM VARCHAR(10),
	CODFORMULA VARCHAR(8),
	VALORDEFAULT VARCHAR(250),
	CODCOLTABDINAM DCODCOLIGADANULL,
	APLICTABDINAM VARCHAR(1))
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE XTYPE='U' AND NAME='ZFCOMPL')
  DROP TABLE ZFCOMPL
GO

CREATE TABLE ZFCOMPL (
        CODCOLIGADA DCODCOLIGADA,
        CHAPA       DCHAPA,
        CONSIDERAFUNCIONARIO VARCHAR(2), 
        COR VARCHAR(46),
        BARBA VARCHAR(46),
        OLHOS VARCHAR(46),
        ALTURA VARCHAR(46),
        PESO VARCHAR(46),
        CABELO VARCHAR(46),
        BIGODE VARCHAR(46),
        NOMEDOPAI VARCHAR(46),
        NOMEDAMAE VARCHAR(46),
        OPTANTEOUNAODEVT VARCHAR(2), 
        OPTANTEDADENTALCORP VARCHAR(2), 
        CENTRODECUSTO VARCHAR(11),
        DEFICIENTEFISICO VARCHAR(2), 
        RACACOR VARCHAR(2), 
        VAGO VARCHAR(2))
GO

INSERT INTO ZFDEPEND
SELECT * FROM PFDEPEND
GO

INSERT INTO ZDEFCOMPL
SELECT * FROM GDEFCOMPL
GO

INSERT INTO ZFCOMPL
SELECT * FROM PFCOMPL
GO

/* 1.1 - FINAL DA CRIAÇÃO E INSERÇÃO DAS TABELAS TEMPORÁRIAS */

PRINT '---- **** 1.1 - FINAL DA CRIAÇÃO E INSERÇÃO DAS TABELAS TEMPORÁRIAS **** ----'
GO


/* 1.2 - DECLARAÇÃO DOS CURSORES PARA INSERÇÃO DOS CAMPOS COMPLEMENTARES PAI E MÃE
         NA TABELA PFDEPEND */

PRINT '---- **** 1.2 - DECLARAÇÃO DOS CURSORES PARA INSERÇÃO DOS CAMPOS COMPLEMENTARES PAI E MÃE
                       NA TABELA PFDEPEND ---- ****'
GO
 
      /* 
        É DEFINIDO QUE NO MOMENTO DA INSERÇÃO O REGISTRO DO PAI, SERÁ GRAVADO COMO
        CÓDIGO DO DEPENDENTE 10, E O REGISTRO DA MÃE COMO CÓDIGO 11
      */

DECLARE @CODCOLIGADA SMALLINT
DECLARE @CHAPA VARCHAR(16)
DECLARE @NOMEDOPAI VARCHAR(46)
DECLARE @NOMEDAMAE VARCHAR(46)

DECLARE CURSOR_PAI CURSOR FOR
  SELECT CODCOLIGADA,CHAPA,NOMEDOPAI 
  FROM PFCOMPL
  WHERE CODCOLIGADA=1 
  ORDER BY CHAPA
OPEN CURSOR_PAI

FETCH NEXT FROM CURSOR_PAI
INTO @CODCOLIGADA,@CHAPA,@NOMEDOPAI

DECLARE CURSOR_MAE CURSOR FOR
  SELECT CODCOLIGADA,CHAPA,NOMEDAMAE
  FROM PFCOMPL
  WHERE CODCOLIGADA=1 
  ORDER BY CHAPA
OPEN CURSOR_MAE

FETCH NEXT FROM CURSOR_MAE
INTO @CODCOLIGADA,@CHAPA,@NOMEDAMAE

WHILE @@FETCH_STATUS = 0
BEGIN
  INSERT INTO PFDEPEND
  (CODCOLIGADA,CHAPA,NRODEPEND,NOME,CPF,DTNASCIMENTO,SEXO,ESTADOCIVIL,
   LOCALNASCIMENTO,CARTORIO,NROREGISTRO,NROLIVRO,NROFOLHA,INCIRRF,INCINSS,
   INCASSISTMEDICA,INCPENSAO,INCDEFINIVEIS,GRAUPARENTESCO,CARTAOVACINA,
   PERCENTUAL,TIPOPENSAO,BANCO,AGENCIA,CONTACORRENTE,RESPONSAVEL,APLICACAO,
   FORCALCULO,BRUTO,DATAENTREGACERTIDAO,FREQESCOLAR,UNIVERSITARIO,INCSALFAM,
   OBSERVACAO,FORMPENSAO)
   VALUES(@CODCOLIGADA,@CHAPA,10,@NOMEDOPAI,NULL,NULL,'M','C',
          NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL,6,0,NULL,NULL,NULL,
          NULL,NULL,NULL,NULL,NULL,0,NULL,0,0,0,NULL,NULL)

  FETCH NEXT FROM CURSOR_PAI
  INTO @CODCOLIGADA,@CHAPA,@NOMEDOPAI

  INSERT INTO PFDEPEND
  (CODCOLIGADA,CHAPA,NRODEPEND,NOME,CPF,DTNASCIMENTO,SEXO,ESTADOCIVIL,
   LOCALNASCIMENTO,CARTORIO,NROREGISTRO,NROLIVRO,NROFOLHA,INCIRRF,INCINSS,
   INCASSISTMEDICA,INCPENSAO,INCDEFINIVEIS,GRAUPARENTESCO,CARTAOVACINA,
   PERCENTUAL,TIPOPENSAO,BANCO,AGENCIA,CONTACORRENTE,RESPONSAVEL,APLICACAO,
   FORCALCULO,BRUTO,DATAENTREGACERTIDAO,FREQESCOLAR,UNIVERSITARIO,INCSALFAM,
   OBSERVACAO,FORMPENSAO)
   VALUES(@CODCOLIGADA,@CHAPA,11,@NOMEDAMAE,NULL,NULL,'F','C',
          NULL,NULL,NULL,NULL,NULL,0,0,0,0,NULL,7,0,NULL,NULL,NULL,
          NULL,NULL,NULL,NULL,NULL,0,NULL,0,0,0,NULL,NULL)

   FETCH NEXT FROM CURSOR_MAE
   INTO @CODCOLIGADA,@CHAPA,@NOMEDAMAE
END

CLOSE CURSOR_PAI
CLOSE CURSOR_MAE
DEALLOCATE CURSOR_PAI
DEALLOCATE CURSOR_MAE

GO

/* 1.2 - FINAL DA DECLARAÇÃO DOS CURSORES PARA INSERÇÃO DOS CAMPOS COMPLEMENTARES PAI E MÃE
         NA TABELA PFDEPEND */

PRINT '---- **** 1.2 - FINAL DA DECLARAÇÃO DOS CURSORES PARA INSERÇÃO DOS CAMPOS COMPLEMENTARES PAI E MÃE
                       NA TABELA PFDEPEND ---- ****'
GO
         
PRINT '---- **** 1.0 - FINAL SCRIPT VALDAC ---- ****'
GO

/* 1.3 - INSERÇÃO DOS TIPOS DE COR/RAÇA NA TABELA PFUNC DE ACORDO COM O CAMPO COMPLEMENTAR CRIADO */

     /* NÃO REALIZADO - ESPERANDO MAIORES INFORMAÇÕES */
   
/* 1.3 - FINAL DA INSERÇÃO DOS TIPOS DE COR/RAÇA NA TABELA PFUNC DE ACORDO COM O CAMPO COMPLEMENTAR CRIADO */

/* 1.0 - FINAL SCRIPT VALDAC */


/*##MAGNA##*/