DECLARE @CODIGO VARCHAR(10)
DECLARE @CODCOLIGADA SMALLINT
DECLARE @TAMANHO INT

DECLARE CURSOR_TROCAEVENTO CURSOR FOR
  SELECT CODCOLIGADA,CODIGO,LEN(CODIGO)
  FROM   PEVENTO 
  WHERE  CODCOLIGADA = 1 

OPEN CURSOR_TROCAEVENTO

FETCH NEXT FROM CURSOR_TROCAEVENTO INTO @CODCOLIGADA,@CODIGO ,@TAMANHO

WHILE @@FETCH_STATUS = 0
BEGIN

  IF @TAMANHO=1
  BEGIN  
   UPDATE PEVENTO SET CODIGO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
  
  UPDATE AABONO  SET CODEVE=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVE=@CODIGO
  
  UPDATE ACOMPFUN   SET  CODEVE=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVE=@CODIGO
  
  UPDATE AEVELAN   SET  CODEVELAN=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVELAN=@CODIGO 
  
  UPDATE AEVEPCOL    SET  CODEVEREL=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVEREL=@CODIGO
  
  UPDATE AMOVFUN    SET  CODEVE=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND	CODEVE= @CODIGO
  
  UPDATE AMOVFUNDIA    SET  CODEVE=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND  CODEVE =@CODIGO   
  
  UPDATE AREFEI  SET  CODEVE=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND  CODEVE=@CODIGO
  
  UPDATE AREFFUN   SET  CODEVE=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVE=@CODIGO
  
  UPDATE AREFVIS   SET  CODEVE=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVE=@CODIGO
  
  UPDATE PADICRESC  SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVENTO= @CODIGO
  
  UPDATE PCOMPRATEIO  SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVENTO= @CODIGO
  
  UPDATE PEVENTO  SET  CODEVENTODIF=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVENTODIF=@CODIGO
  
  UPDATE PEVENTO    SET  CODEVENTOINSUF=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVENTOINSUF=@CODIGO
  
  UPDATE PEVTBASESALCMP  SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND	CODEVENTO=@CODIGO
  
  UPDATE PEVTBASESALCMP  SET  CODEVENTOSALCMP=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVENTOSALCMP=@CODIGO
  
  UPDATE PEVTCOMPOSICAO  SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND	 CODEVENTO= @CODIGO
  
  UPDATE PEVTGRP    SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND  CODEVENTO=@CODIGO
  
  UPDATE PEVTMED    SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND  CODEVENTO= @CODIGO
  
  UPDATE PFADICFER  SET  CODEVTFOLHA=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVTFOLHA=@CODIGO
  
  UPDATE PFADICFER  SET  EVENTOFOLHAMESANT=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND EVENTOFOLHAMESANT=@CODIGO
  
  UPDATE PFADICFER  SET  EVENTOFOLHAPROXMES=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND EVENTOFOLHAPROXMES=@CODIGO
  
  UPDATE PFADICFER  SET  CODEVTRECIBO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVTRECIBO=@CODIGO
  
  UPDATE PFADICFER  SET  EVENTORECPROXMES=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND EVENTORECPROXMES=@CODIGO
  
  UPDATE PFCODFIX    SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
  
  UPDATE PFDEPEVENTOS    SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVENTO=@CODIGO
  
  UPDATE PFEMPRT  SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
  
  UPDATE PFFERIAS   SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
  
  UPDATE PFFINANC   SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVENTO=@CODIGO
  
  UPDATE PFFINANCCOMPL    SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVENTO=@CODIGO
  
  UPDATE PFHSTSAL   SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
  
  UPDATE PFMOVCC  SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND   CODEVENTO=@CODIGO
  
  UPDATE PFMOVCCCOMPL    SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVENTO=@CODIGO
  
  UPDATE PFMOVTOMADOR    SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
  
  UPDATE PFSALCMP    SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
  
  UPDATE PFUNC   SET  EVTADIANTFERIAS=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	EVTADIANTFERIAS=@CODIGO
  
  UPDATE PFVERBAS   SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
  
  UPDATE PFVERBASCOMPL    SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
  
  UPDATE PGADIC13  SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVENTO=@CODIGO
  
  UPDATE PGADICFER   SET  CODEVTFOLHA=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	CODEVTFOLHA=@CODIGO
  
  UPDATE PGADICFER  SET  EVENTOFOLHAMESANT=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND EVENTOFOLHAMESANT= @CODIGO
  
  UPDATE PGADICFER  SET  EVENTOFOLHAPROXMES=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND EVENTOFOLHAPROXMES=@CODIGO
  
  UPDATE PGADICFER  SET  CODEVTRECIBO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVTRECIBO=@CODIGO
  
  UPDATE PGADICFER    SET  EVENTORECPROXMES=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  EVENTORECPROXMES=@CODIGO
  
  UPDATE PPARAM    SET  EVTSALDOSALARIO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND EVTSALDOSALARIO=@CODIGO
  
  UPDATE PPARAM    SET  EVTDESCEMPRESTIMO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND EVTDESCEMPRESTIMO=@CODIGO
  
  UPDATE PPARAM    SET  EVTPROVEMPRESTIMO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  EVTPROVEMPRESTIMO=@CODIGO
  
  UPDATE PPARDIRF  SET  EVTRESTITUICAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	EVTRESTITUICAO=@CODIGO
  
  UPDATE PPARRESC   SET  CODEVTRESCCPLDESC=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVTRESCCPLDESC=@CODIGO
  
  UPDATE PPARRESC SET  CODEVTRESCCPL=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	 CODEVTRESCCPL=@CODIGO
  
  UPDATE PSINDEVT SET  CODEVENTODIF=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	  CODEVENTODIF=@CODIGO
  
  UPDATE PSINDEVT SET  CODEVENTOENV=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	 CODEVENTOENV=@CODIGO
  
  UPDATE PSINDEVT SET  CODEVENTOPAGTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTOPAGTO=@CODIGO
  
  UPDATE VBENEFICIOS SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	CODEVENTO=@CODIGO
  
  UPDATE VMOVFUNC   SET  CODEVENTO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
   END    
  ELSE 
    IF @TAMANHO=2  
    BEGIN  
    UPDATE PEVENTO SET CODIGO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
        
        UPDATE AABONO  SET  CODEVE=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVE=@CODIGO
        
        UPDATE ACOMPFUN   SET  CODEVE=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVE=@CODIGO
        
        UPDATE AEVELAN   SET  CODEVELAN=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVELAN=@CODIGO 
        
        UPDATE AEVEPCOL    SET  CODEVEREL=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVEREL=@CODIGO
        
        UPDATE AMOVFUN    SET  CODEVE=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND	CODEVE= @CODIGO
        
        UPDATE AMOVFUNDIA    SET  CODEVE=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND  CODEVE =@CODIGO   
        
        UPDATE AREFEI  SET  CODEVE=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND  CODEVE=@CODIGO
        
        UPDATE AREFFUN   SET  CODEVE=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND	CODEVE=@CODIGO
        
        UPDATE AREFVIS   SET  CODEVE=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND	CODEVE=@CODIGO
        
        UPDATE PADICRESC  SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVENTO= @CODIGO
        
        UPDATE PCOMPRATEIO  SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVENTO= @CODIGO
        
        UPDATE PEVENTO  SET  CODEVENTODIF=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVENTODIF=@CODIGO
        
        UPDATE PEVENTO    SET  CODEVENTOINSUF=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVENTOINSUF=@CODIGO
        
        UPDATE PEVTBASESALCMP  SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND	CODEVENTO=@CODIGO
        
        UPDATE PEVTBASESALCMP  SET  CODEVENTOSALCMP=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVENTOSALCMP=@CODIGO
        
        UPDATE PEVTCOMPOSICAO  SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND	 CODEVENTO= @CODIGO
        
        UPDATE PEVTGRP    SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND  CODEVENTO=@CODIGO
        
        UPDATE PEVTMED    SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND  CODEVENTO= @CODIGO
        
        UPDATE PFADICFER  SET  CODEVTFOLHA=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVTFOLHA=@CODIGO
        
        UPDATE PFADICFER  SET  EVENTOFOLHAMESANT=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND EVENTOFOLHAMESANT=@CODIGO
        
        UPDATE PFADICFER  SET  EVENTOFOLHAPROXMES=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND EVENTOFOLHAPROXMES=@CODIGO
        
        UPDATE PFADICFER  SET  CODEVTRECIBO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODEVTRECIBO=@CODIGO
        
        UPDATE PFADICFER  SET  EVENTORECPROXMES=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND EVENTORECPROXMES=@CODIGO
        
        UPDATE PFCODFIX    SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
        
        UPDATE PFDEPEVENTOS    SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVENTO=@CODIGO
        
        UPDATE PFEMPRT  SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
        
        UPDATE PFFERIAS   SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
        
        UPDATE PFFINANC   SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVENTO=@CODIGO
        
        UPDATE PFFINANCCOMPL    SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVENTO=@CODIGO
        
        UPDATE PFHSTSAL   SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
        
        UPDATE PFMOVCC  SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND   CODEVENTO=@CODIGO
        
        UPDATE PFMOVCCCOMPL    SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVENTO=@CODIGO
        
        UPDATE PFMOVTOMADOR    SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
        
        UPDATE PFSALCMP    SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
        
        UPDATE PFUNC   SET  EVTADIANTFERIAS=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	EVTADIANTFERIAS=@CODIGO
        
        UPDATE PFVERBAS   SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
        
        UPDATE PFVERBASCOMPL    SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
        
        UPDATE PGADIC13  SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVENTO=@CODIGO
        
        UPDATE PGADICFER   SET  CODEVTFOLHA=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	CODEVTFOLHA=@CODIGO
        
        UPDATE PGADICFER  SET  EVENTOFOLHAMESANT=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND EVENTOFOLHAMESANT= @CODIGO
        
        UPDATE PGADICFER  SET  EVENTOFOLHAPROXMES=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND EVENTOFOLHAPROXMES=@CODIGO
        
        UPDATE PGADICFER  SET  CODEVTRECIBO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND CODEVTRECIBO=@CODIGO
        
        UPDATE PGADICFER    SET  EVENTORECPROXMES=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  EVENTORECPROXMES=@CODIGO
        
        UPDATE PPARAM    SET  EVTSALDOSALARIO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND EVTSALDOSALARIO=@CODIGO
        
        UPDATE PPARAM    SET  EVTDESCEMPRESTIMO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND EVTDESCEMPRESTIMO=@CODIGO
        
        UPDATE PPARAM    SET  EVTPROVEMPRESTIMO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  EVTPROVEMPRESTIMO=@CODIGO
        
        UPDATE PPARDIRF  SET  EVTRESTITUICAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	EVTRESTITUICAO=@CODIGO
        UPDATE PPARRESC   SET  CODEVTRESCCPLDESC=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVTRESCCPLDESC=@CODIGO
        UPDATE PPARRESC SET  CODEVTRESCCPL=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	 CODEVTRESCCPL=@CODIGO
        UPDATE PSINDEVT SET  CODEVENTODIF=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	  CODEVENTODIF=@CODIGO
        UPDATE PSINDEVT SET  CODEVENTOENV=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	 CODEVENTOENV=@CODIGO
        UPDATE PSINDEVT SET  CODEVENTOPAGTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTOPAGTO=@CODIGO
        UPDATE VBENEFICIOS SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND	CODEVENTO=@CODIGO
        UPDATE VMOVFUNC   SET  CODEVENTO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA  AND  CODEVENTO=@CODIGO
       END  
      ELSE
    UPDATE PEVENTO SET CODIGO=@CODIGO WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO  
    
      FETCH NEXT FROM CURSOR_TROCAEVENTO INTO @CODIGO  
  END
      
    CLOSE CURSOR_TROCAEVENTO
  DEALLOCATE CURSOR_TROCAEVENTO 
