/***********************************************************/
/* CLIENTE:                  IRON MOUNTAIN / SSG           */
/* BANCO DE DADOS:           MSSQL                         */
/* VERSÃO DO BANCO DE DADOS: 7.0 - 54                      */
/* VERSÃO DA BASE DE DADOS:  4.01                          */
/* DATA DE CRIAÇÃO:          31/07/2002                    */
/* ANALISTA RESPONSÁVEL:     FUMIO                         */
/* OCORRÊNCIA RMAGILIS:                                    */
/* OBJETIVO:                 REMOVER OS DADOS DA COLIGADA X*/
/*                           DE TODAS AS TABELAS COM       */ 
/*                           EXCESSÃO DAS TABELAS GLOBAIS  */
/***********************************************************/


CREATE PROCEDURE DELETE_COLIGADA @CODCOL SMALLINT
AS  

DECLARE @COL VARCHAR(5)
DECLARE @TABNAME VARCHAR(255)
DECLARE @COLNAME VARCHAR(255)
DECLARE @ID INT
DECLARE @SQLSTR VARCHAR(255)


SET NOCOUNT ON

SELECT @COL=CONVERT(VARCHAR,@CODCOL)

DECLARE TABS CURSOR FOR 
  SELECT ID,NAME 
  FROM SYSOBJECTS 
  WHERE ID IN (SELECT DISTINCT ID 
               FROM SYSCOLUMNS 
               WHERE NAME = 'CODCOLIGADA') 
  AND XTYPE='U'
  AND NAME NOT LIKE 'G%'
  ORDER BY NAME

OPEN TABS
FETCH NEXT FROM TABS INTO @ID,@TABNAME

WHILE (@@FETCH_STATUS=0)
BEGIN
  SELECT @SQLSTR='DELETE FROM ' + @TABNAME + ' WHERE CODCOLIGADA=' + @COL
  EXEC(@SQLSTR)
  PRINT @SQLSTR
  FETCH NEXT FROM TABS INTO @ID,@TABNAME
END
CLOSE TABS
DEALLOCATE TABS

DECLARE TABS CURSOR FOR 
  SELECT ID,NAME 
  FROM SYSOBJECTS 
  WHERE NAME IN ('GRAT','OFACESSORIOOBJ','OFITMPLANO','OFMODELO','OFOPCIONAL','TITMMOVRELAC','TMOVRELAC') 
  ORDER BY NAME

OPEN TABS
FETCH NEXT FROM TABS INTO @ID,@TABNAME

WHILE (@@FETCH_STATUS=0)
BEGIN  
  DECLARE COLS CURSOR FOR 
    SELECT NAME 
    FROM SYSCOLUMNS 
    WHERE NAME LIKE 'CODCOL%' 
    AND ID=@ID
  OPEN COLS
  FETCH NEXT FROM COLS INTO @COLNAME
 
  WHILE (@@FETCH_STATUS=0)
  BEGIN
    SELECT @SQLSTR='DELETE FROM ' + @TABNAME + ' WHERE ' + @COLNAME + '=' + @COL
    EXEC(@SQLSTR)
    PRINT @SQLSTR
    FETCH NEXT FROM COLS INTO @COLNAME
  END
  CLOSE COLS
  DEALLOCATE COLS
  FETCH NEXT FROM TABS INTO @ID,@TABNAME
END
CLOSE TABS
DEALLOCATE TABS
GO


/*##MAGNA##*/