--DROP PROCEDURE SP_CHECKTABLES_RM
CREATE PROCEDURE SP_CHECKTABLES_RM
AS

DECLARE @TABLENAME VARCHAR(30)
DECLARE @TABLENAME_HEADER VARCHAR(75)

DECLARE TNAMES_CURSOR CURSOR FOR 
  SELECT NAME FROM SYSOBJECTS
  WHERE TYPE = 'U'
  ORDER BY NAME
      
OPEN TNAMES_CURSOR
FETCH NEXT FROM TNAMES_CURSOR INTO @TABLENAME

PRINT '*************  INÍCIO DE CHECAGEM DAS TABELAS  *************'
PRINT ' '

WHILE (@@FETCH_STATUS <> -1)
BEGIN
  IF (@@FETCH_STATUS <> -2)
  BEGIN
    SELECT @TABLENAME_HEADER = 'ATUALIZANDO TABELA '  + RTRIM(UPPER(@TABLENAME))
    PRINT '========== '+@TABLENAME_HEADER+' =========='
    PRINT 'ATUALIZANDO ESTATÍSTICAS DA TABELA '+ @TABLENAME
    EXEC ('UPDATE STATISTICS '  + @TABLENAME )
    PRINT ' '
    PRINT 'REINDEXANDO OS INDICES DA TABELA '+ @TABLENAME
    EXEC ('DBCC DBREINDEX (' +@TABLENAME+')')
    PRINT ' '
    PRINT 'VERIFICANDO ESTRUTUTURA DA TABELA '+ @TABLENAME
    EXEC ('DBCC CHECKTABLE (' +@TABLENAME+')')
    PRINT ' '
  END
  FETCH NEXT FROM TNAMES_CURSOR INTO @TABLENAME
END
PRINT ' '
PRINT '*************  FINAL DE CHECAGEM DAS TABELAS  *************'
PRINT @TABLENAME_HEADER
PRINT ' '
DEALLOCATE TNAMES_CURSOR
GO
