/*************************************************************/
/* CLIENTE:                  STAMP                           */
/* BANCO DE DADOS:           MSSQL                           */
/* VERSÃO DO BANCO DE DADOS: 7.0 - 54                        */
/* VERSÃO DA BASE DE DADOS:  4.02                            */
/* DATA DE CRIAÇÃO:          20/06/2002                      */
/* ANALISTA RESPONSÁVEL:     FUMIO                           */
/* OCORRÊNCIA RMAGILIS:                                      */
/* OBJETIVO:                 REALOCAÇÃO DAS TABELAS DINÂMICAS*/
/*                           PARA AS OUTRAS COLIGADAS QUE NÃO*/ 
/*                           SÃO TRATADAS NO SCRIPT DA BASE  */
/*                           VAZIA                           */
/*************************************************************/

/* CRIAÇÃO DAS TABELAS TEMPORÁRIAS */
CREATE TABLE ZGDINAM (
	CODCOLIGADA DCODCOLIGADA,
	APLICACAO VARCHAR(1) NOT NULL,
	CODIGO VARCHAR(10) NOT NULL,
	FINALIDADE SMALLINT,
	DESCRICAO VARCHAR(50),
	NOMETABELA VARCHAR(15))
GO

CREATE TABLE ZPCODGRPAAS (
	CODCOLIGADA DCODCOLIGADA,
	CODCLIENTE SMALLINT NOT NULL,
	CODINTERNO SMALLINT NOT NULL,
	DESCRICAO VARCHAR(50),
	PODEALTERAR SMALLINT)
GO

CREATE TABLE ZPSERVBANCO (
	CODCOLIGADA DCODCOLIGADA,
	CODTABELA VARCHAR(10) NOT NULL,
	CODCLIENTE VARCHAR(5) NOT NULL,
	CODINTERNO VARCHAR(5) NOT NULL,
	DESCRICAO VARCHAR(50),
	PODEALTERAR SMALLINT,
	APLICACAO VARCHAR(1) DEFAULT 'P' NOT NULL)
GO

/*INSERÇÃO DE REGISTROS NAS TABELAS TEMPORÁRIAS*/
INSERT INTO ZGDINAM
SELECT * FROM GDINAM
GO
INSERT INTO ZPCODGRPAAS
SELECT * FROM PCODGRPAAS
GO
INSERT INTO ZPSERVBANCO
SELECT * FROM PSERVBANCO
GO

/* REMOVENDO OS RELACIONAMENTOS DAS TABELAS */
ALTER TABLE GCONSIST DROP CONSTRAINT FKGCONSIST_GDINAM
GO
ALTER TABLE GDEFCOMPL DROP CONSTRAINT FKGDEFCOMPL_GDINAM
GO
ALTER TABLE PBCOSERV DROP CONSTRAINT FKPBCOSERV_GDINAM
GO
ALTER TABLE PSERVBANCO DROP CONSTRAINT FKPSERVBANCO_GDINAM
 
/*LIMPANDO AS TABELAS*/
DELETE FROM GDINAM
GO
DELETE FROM PCODGRPAAS
GO
DELETE FROM PSERVBANCO
GO

/*INSERINDO NAS TABELAS OFICIAIS */

/*** TABELA: GDINAM ***/

INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'G', 'GTPFERIADO', 3, 'Tipo de feriado', 'GTPFERIADO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'CODLANATIV', 3, 'Código de lançamento ativo', 'PLANATIVO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'CODLANFIN', 0, 'Lançamento financeiro', 'PCODLANFIN')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT01', 0, 'Tipo de encargo', 'PTPENCARGO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT02', 0, 'Indicador de contribuição sindical', 'PCODCTSIND')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT03', 0, 'Grau de parentesco', 'PCODPARENT')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT04', 0, 'Código de recebimento', 'PCODRECEB')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT05', 0, 'Tipo de demissão', 'PTPDEMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT06', 0, 'Código de situação', 'PCODSITUACAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT07', 0, 'Código de afastamento', 'PCODAFAST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT08', 0, 'Nacionalidade', 'PCODNACAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT09', 0, 'Grau de instrução', 'PCODINSTRUCAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT10', 3, 'Estado civil', 'PCODESTCIVIL')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT11', 0, 'Tipo de admissão', 'PTPADMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT12', 0, 'Situação para RAIS', 'PCODSITRAIS')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT13', 0, 'Vínculo', 'PCODVINCULO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT14', 0, 'Opção por FGTS', 'PCODSITFGTS')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT15', 0, 'Sexo', 'PCODSEXO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT16', 0, 'Tipo de funcionário', 'PTPFUNC')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT17', 0, 'Código de saque FGTS', 'PCODSAQUE')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT18', 0, 'Meio de transporte', 'PMEIOTRANSP')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT19', 0, 'Código de cálculo', 'PCODCALCULO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT38', 0, 'Categoria do empregador', 'PCATEGEMP')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT39', 0, 'Causa de mudança do CGC', 'PCAUSAMUDCGC')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT40', 3, 'Tipo de anotação', 'PTPANOTACAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT41', 0, 'Tipo de Rendimento para DIRF/Informe Rendimentos', 'PTPRENDIMENTOS')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT42', 3, 'Tipo de Código Fixo', 'PTPCODFIXO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT43', 0, 'Categoria de Trabalhador', 'PCODCATTRAB')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT44', 0, 'Ocorrência do Trabalhador', 'PCODOCORTRAB')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT45', 3, 'Tipo de pensão alimentícia', 'PTPPENSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT46', 0, 'Cor/Raça', 'PCORRACA')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT47', 0, 'Porte Empresa', 'PPORTEEMPRESA')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'INT49', 0, 'Tipos de avisos automáticos', 'PTPAVISO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'P', 'PCODATIVO', 3, 'Código encargo ativo', 'PCODATIVO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'U', 'INT04', 2, 'ESCOLARIDADE', 'PCODINSTRUCAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'U', 'INT05', 0, 'VINCULO EMPREGATICIO', 'PCODVINCULO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'U', 'INT06', 3, 'SITUACAO CIVIL', 'PCODESTCIVIL')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'U', 'INT07', 0, 'NACIONALIDADES', 'PCODNACAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'U', 'INT09', 0, 'TIPOS DE PARENTESCO', 'PCODPARENT')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'V', 'INT04', 0, 'Código de recebimento', 'PCODRECEB')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'V', 'INT05', 0, 'Tipo de demissão', 'PTPDEMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'V', 'INT06', 0, 'Código de situação', 'PCODSITUACAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'V', 'INT08', 0, 'Nacionalidade', 'PCODNACAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'V', 'INT09', 0, 'Grau de instrução', 'PCODINSTRUCAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'V', 'INT11', 0, 'Tipo de admissão', 'PTPADMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'V', 'INT15', 0, 'Sexo', 'PCODSEXO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'V', 'INT16', 0, 'Tipo de funcionário', 'PTPFUNC')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'V', 'INT17', 0, 'Código de saque FGTS', 'PCODSAQUE')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (0, 'V', 'INT40', 3, 'Tipo de anotação', 'PTPANOTACAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'F', 'DATA', 2, 'DATA TESTE', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', '02', 2, 'somente folha', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'BANESTADO', 1, 'Tipo de pagamento BANESTADO', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'BANESTES', 1, 'Forma de pagamento BANESTES', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco001', 1, 'Servico do Banco do Brasil', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco008', 1, 'Servico do Banco Meridional', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco022', 1, 'Servico do Banco Credireal', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco033', 1, 'Servico do BANESPA', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco153', 1, 'Servico do Banco C.E.E.R.G.S.', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco275', 1, 'Servico do Banco Real', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco291', 1, 'Natureza de Credito BCN', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco334', 1, 'Forma pagto do Excel Economico', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco409', 1, 'Servico do Banco Unibanco', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco415', 1, 'Servico do Banco Nacional', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco420', 1, 'Classe de titulo do BANORTE', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'Bco422', 1, 'Ident. alter. saldo Banco Safra', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'CODINTCONT', 3, 'Código para a integração contábil', 'PCODINTCONT')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'CODINTGER', 3, 'Código para a integração gerencial', 'PCODINTGER')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'GRPCONT', 3, 'Grupo de contas contábeis', 'PGRPCONTACONT')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'GRPGER', 3, 'Grupo de contas gerenciais', 'PGRPCONTAGER')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'indicacao', 2, 'Tabela de indicação', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT20', 3, 'Grupo de compra de vale transporte', 'PGRPVALE')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT21', 3, 'Codigo de itinerario', 'PCODITINER')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT22', 3, 'Motivo de admissao', 'PMOTADMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT23', 3, 'Motivo de demissao', 'PMOTDEMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT24', 3, 'Motivo de mudanca de secao', 'PMOTMUDSECAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT25', 3, 'Motivo de mudanca de funcao', 'PMOTMUDFUNCAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT26', 3, 'Motivo de mudanca de salario', 'PMOTMUDSAL')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT28', 3, 'Motivo de mudanca de situacao', 'PMUDSITUACAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT29', 3, 'Mensagem de critica da folha de pagamento', 'PMSGCRITICA')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT30', 3, 'Codigo de emprestimo', 'PCODEMPRT')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT32', 3, 'Codigo de valor de sindicato', 'PCODVALSIND')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT33', 3, 'Nome de totalizador', 'PCODTOTALIZ')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT34', 3, 'Nome de acumulador', 'PCODACUM')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT35', 3, 'Nome do grupo de AAS', 'PCODGRPAAS')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT36', 3, 'Codigo de valor de secao', 'PCODVALSEC')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT37', 3, 'Nome de incidencia de dependente', 'PCODINCDEP')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INT48', 3, 'Codigo de valor de funcionario', 'PCODVALFUNC')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INTCONTFUN', 3, 'Código para Integração contábil de funcionários', 'PCODINTCONTFUNC')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'INTGERFUNC', 3, 'Código para Integração gerencial de funcionários', 'PCODINTGERFUNC')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'SANGUE', 2, 'Validacao de tipo sanguineo', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'P', 'TABCONFBB', 2, 'Conferência layout bancário Banco do Brasil', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'T', '1', 2, '1', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'U', 'INT01', 3, 'RELIGIOES', 'ERELIG')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'U', 'INT02', 3, 'PROFISSOES', 'EPROFISS')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'U', 'INT03', 3, 'OCUPACOES', 'ETABOCUP')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'U', 'INT10', 3, 'LINGUAS', 'ETABLINGUAS')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', '01', 2, 'Tipos sanguíneos', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'CATEMITE', 2, 'Tipo de Emitente da CAT', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'CATFILPREV', 2, 'Tipo de Filiação à Previdência Social', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'CATSIMNAO', 2, 'Validação SIM / NÃO', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'CATTIPO', 2, 'Tipo de CAT', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'indicacao', 2, 'Tabela de Indicadores para recrutamento', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'INT22', 3, 'Motivo de admissao', 'PMOTADMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'INT23', 3, 'Motivo de demissao', 'PMOTDEMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'INT24', 3, 'Motivo de mudanca de secao', 'PMOTMUDSECAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'INT25', 3, 'Motivo de mudanca de funcao', 'PMOTMUDFUNCAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'INT26', 3, 'Motivo de mudanca de salario', 'PMOTMUDSAL')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'INT28', 3, 'Motivo de mudanca de situacao', 'PMUDSITUACAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (1, 'V', 'TD_001', 3, 'Tipos de gráfico', 'VTIPOGRAF')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'F', 'DATA', 2, 'DATA TESTE', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', '02', 2, 'somente folha', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'BANESTADO', 1, 'Tipo de pagamento BANESTADO', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'BANESTES', 1, 'Forma de pagamento BANESTES', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco001', 1, 'Servico do Banco do Brasil', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco008', 1, 'Servico do Banco Meridional', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco022', 1, 'Servico do Banco Credireal', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco033', 1, 'Servico do BANESPA', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco153', 1, 'Servico do Banco C.E.E.R.G.S.', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco275', 1, 'Servico do Banco Real', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco291', 1, 'Natureza de Credito BCN', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco334', 1, 'Forma pagto do Excel Economico', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco409', 1, 'Servico do Banco Unibanco', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco415', 1, 'Servico do Banco Nacional', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco420', 1, 'Classe de titulo do BANORTE', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'Bco422', 1, 'Ident. alter. saldo Banco Safra', 'PSERVBANCO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'CODINTCONT', 3, 'Código para a integração contábil', 'PCODINTCONT')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'CODINTGER', 3, 'Código para a integração gerencial', 'PCODINTGER')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'GRPCONT', 3, 'Grupo de contas contábeis', 'PGRPCONTACONT')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'GRPGER', 3, 'Grupo de contas gerenciais', 'PGRPCONTAGER')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'indicacao', 2, 'Tabela de indicação', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT20', 3, 'Grupo de compra de vale transporte', 'PGRPVALE')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT21', 3, 'Codigo de itinerario', 'PCODITINER')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT22', 3, 'Motivo de admissao', 'PMOTADMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT23', 3, 'Motivo de demissao', 'PMOTDEMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT24', 3, 'Motivo de mudanca de secao', 'PMOTMUDSECAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT25', 3, 'Motivo de mudanca de funcao', 'PMOTMUDFUNCAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT26', 3, 'Motivo de mudanca de salario', 'PMOTMUDSAL')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT28', 3, 'Motivo de mudanca de situacao', 'PMUDSITUACAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT29', 3, 'Mensagem de critica da folha de pagamento', 'PMSGCRITICA')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT30', 3, 'Codigo de emprestimo', 'PCODEMPRT')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT32', 3, 'Codigo de valor de sindicato', 'PCODVALSIND')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT33', 3, 'Nome de totalizador', 'PCODTOTALIZ')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT34', 3, 'Nome de acumulador', 'PCODACUM')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT35', 3, 'Nome do grupo de AAS', 'PCODGRPAAS')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT36', 3, 'Codigo de valor de secao', 'PCODVALSEC')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT37', 3, 'Nome de incidencia de dependente', 'PCODINCDEP')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INT48', 3, 'Codigo de valor de funcionario', 'PCODVALFUNC')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INTCONTFUN', 3, 'Código para Integração contábil de funcionários', 'PCODINTCONTFUNC')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'INTGERFUNC', 3, 'Código para Integração gerencial de funcionários', 'PCODINTGERFUNC')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'SANGUE', 2, 'Validacao de tipo sanguineo', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'P', 'TABCONFBB', 2, 'Conferência layout bancário Banco do Brasil', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'T', '1', 2, '1', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'U', 'INT01', 3, 'RELIGIOES', 'ERELIG')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'U', 'INT02', 3, 'PROFISSOES', 'EPROFISS')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'U', 'INT03', 3, 'OCUPACOES', 'ETABOCUP')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'U', 'INT10', 3, 'LINGUAS', 'ETABLINGUAS')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', '01', 2, 'Tipos sanguíneos', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'CATEMITE', 2, 'Tipo de Emitente da CAT', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'CATFILPREV', 2, 'Tipo de Filiação à Previdência Social', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'CATSIMNAO', 2, 'Validação SIM / NÃO', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'CATTIPO', 2, 'Tipo de CAT', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'indicacao', 2, 'Tabela de Indicadores para recrutamento', 'GCONSIST')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'INT22', 3, 'Motivo de admissao', 'PMOTADMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'INT23', 3, 'Motivo de demissao', 'PMOTDEMISSAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'INT24', 3, 'Motivo de mudanca de secao', 'PMOTMUDSECAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'INT25', 3, 'Motivo de mudanca de funcao', 'PMOTMUDFUNCAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'INT26', 3, 'Motivo de mudanca de salario', 'PMOTMUDSAL')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'INT28', 3, 'Motivo de mudanca de situacao', 'PMUDSITUACAO')
GO
INSERT INTO GDINAM (CODCOLIGADA, APLICACAO, CODIGO, FINALIDADE, DESCRICAO, NOMETABELA)
 VALUES (2, 'V', 'TD_001', 3, 'Tipos de gráfico', 'VTIPOGRAF')
GO

/*** TABELA: PCODGRPAAS ***/

INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (1, 0, 0, 'Grupo AAS 00', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (1, 1, 1, 'Salario', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (1, 2, 2, 'Horas Extras', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (1, 3, 3, 'Adicional Noturno', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (1, 4, 4, 'Gratificacoes/Comissoes', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (1, 5, 5, 'Produtividade', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (1, 6, 6, 'Ferias', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (1, 7, 7, '13o Salario', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (1, 8, 8, 'Insalubridade', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (2, 0, 0, 'Grupo AAS 00', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (2, 1, 1, 'Salario', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (2, 2, 2, 'Horas Extras', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (2, 3, 3, 'Adicional Noturno', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (2, 4, 4, 'Gratificacoes/Comissoes', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (2, 5, 5, 'Produtividade', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (2, 6, 6, 'Ferias', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (2, 7, 7, '13o Salario', 0)
GO
INSERT INTO PCODGRPAAS (CODCOLIGADA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR)
 VALUES (2, 8, 8, 'Insalubridade', 0)
GO

/*** TABELA: PSERVBANCO ***/

INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'BANESTADO', '0', '0', 'Cheque ou credito em C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'BANESTADO', '1', '1', 'Cred. em C/C ou cta.poo', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'BANESTADO', '2', '2', 'Ch.frac. ou cred. em C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'BANESTADO', '4', '4', 'Debito em C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'BANESTES', '1', '1', 'Cheque salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'BANESTES', '2', '2', 'Ch.Sal. fracionado', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'BANESTES', '3', '3', 'Credito em C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'BANESTES', '4', '4', 'Recibo pagamento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco001', '001', '001', 'Proventos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco001', '002', '002', 'Av. Credito', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco001', '003', '003', 'Acoes-Divid', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco001', '004', '004', 'Beneficio', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco001', '010', '010', 'DP. BL. IND', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco001', '017', '017', 'DOC Credito', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco001', '056', '056', 'Cartao Salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco008', '001', '001', 'Cred. salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco008', '002', '002', 'Cred. comissoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco008', '003', '003', 'Cred. dividendos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco008', '004', '004', 'Cred. pensoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco008', '999', '999', 'Outros', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco022', '001', '001', 'Salarios', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco022', '002', '002', 'Comissoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco022', '003', '003', 'Empresas', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco022', '004', '004', 'Pensoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco022', '999', '999', 'Debito', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco033', '001', '001', 'Credito Salarios', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco033', '002', '002', 'Credito Comissoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco033', '003', '003', 'Credito Dividendos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco033', '004', '004', 'Credito Pensoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco033', '999', '999', 'Outros cred./deb.', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco153', '013', '013', 'Pagto. no dia', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco153', '020', '020', 'Pagto. em 24h', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco153', '151', '151', 'Pagto. em 48h', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco153', '152', '152', 'Pagto. em 72h', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco153', '216', '216', 'Crd folha pgto', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco275', '001', '001', 'Proventos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco275', '002', '002', 'Diversos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco275', '003', '003', 'Dividendos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco275', '004', '004', 'Abono', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco291', '1', '1', 'Pagamento normal', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco291', '2', '2', 'Abono', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco291', '3', '3', 'Complemento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco291', '4', '4', 'Adiant. salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco291', '5', '5', 'Adiant. ferias', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco291', '6', '6', '13o salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco334', '01', '01', 'Credito C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco334', '02', '02', 'Cheque Admin.', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco334', '03', '03', 'Ordem Pagamento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco334', '04', '04', 'DOC - Doc.Cred.', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco334', '05', '05', 'Autent. docum.', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco334', '06', '06', 'Envelopamento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco409', '1', '1', 'Salarios', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco409', '2', '2', 'Fornecedores', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco409', '3', '3', 'Terceiros', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco409', '4', '4', 'Servicos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco415', '337', '337', 'Credito com recibo', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco415', '355', '355', 'Credito C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco415', '737', '737', 'RPS Recibo', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco415', '755', '755', 'RPS Envelopamento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco415', '855', '855', 'Cartao Salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco420', '01', '01', 'Compensacao', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco420', '02', '02', 'Cheque Admin.', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco420', '03', '03', 'Credito C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco420', '05', '05', 'Ordem Pagamento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco420', '06', '06', 'DOC Credito', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco420', '10', '10', 'Cheque Salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco422', '1', '1', 'On line', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (1, 'Bco422', '2', '2', 'Batch', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'BANESTADO', '0', '0', 'Cheque ou credito em C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'BANESTADO', '1', '1', 'Cred. em C/C ou cta.poo', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'BANESTADO', '2', '2', 'Ch.frac. ou cred. em C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'BANESTADO', '4', '4', 'Debito em C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'BANESTES', '1', '1', 'Cheque salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'BANESTES', '2', '2', 'Ch.Sal. fracionado', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'BANESTES', '3', '3', 'Credito em C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'BANESTES', '4', '4', 'Recibo pagamento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco001', '001', '001', 'Proventos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco001', '002', '002', 'Av. Credito', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco001', '003', '003', 'Acoes-Divid', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco001', '004', '004', 'Beneficio', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco001', '010', '010', 'DP. BL. IND', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco001', '017', '017', 'DOC Credito', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco001', '056', '056', 'Cartao Salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco008', '001', '001', 'Cred. salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco008', '002', '002', 'Cred. comissoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco008', '003', '003', 'Cred. dividendos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco008', '004', '004', 'Cred. pensoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco008', '999', '999', 'Outros', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco022', '001', '001', 'Salarios', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco022', '002', '002', 'Comissoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco022', '003', '003', 'Empresas', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco022', '004', '004', 'Pensoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco022', '999', '999', 'Debito', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco033', '001', '001', 'Credito Salarios', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco033', '002', '002', 'Credito Comissoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco033', '003', '003', 'Credito Dividendos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco033', '004', '004', 'Credito Pensoes', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco033', '999', '999', 'Outros cred./deb.', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco153', '013', '013', 'Pagto. no dia', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco153', '020', '020', 'Pagto. em 24h', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco153', '151', '151', 'Pagto. em 48h', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco153', '152', '152', 'Pagto. em 72h', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco153', '216', '216', 'Crd folha pgto', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco275', '001', '001', 'Proventos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco275', '002', '002', 'Diversos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco275', '003', '003', 'Dividendos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco275', '004', '004', 'Abono', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco291', '1', '1', 'Pagamento normal', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco291', '2', '2', 'Abono', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco291', '3', '3', 'Complemento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco291', '4', '4', 'Adiant. salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco291', '5', '5', 'Adiant. ferias', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco291', '6', '6', '13o salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco334', '01', '01', 'Credito C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco334', '02', '02', 'Cheque Admin.', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco334', '03', '03', 'Ordem Pagamento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco334', '04', '04', 'DOC - Doc.Cred.', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco334', '05', '05', 'Autent. docum.', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco334', '06', '06', 'Envelopamento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco409', '1', '1', 'Salarios', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco409', '2', '2', 'Fornecedores', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco409', '3', '3', 'Terceiros', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco409', '4', '4', 'Servicos', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco415', '337', '337', 'Credito com recibo', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco415', '355', '355', 'Credito C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco415', '737', '737', 'RPS Recibo', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco415', '755', '755', 'RPS Envelopamento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco415', '855', '855', 'Cartao Salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco420', '01', '01', 'Compensacao', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco420', '02', '02', 'Cheque Admin.', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco420', '03', '03', 'Credito C/C', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco420', '05', '05', 'Ordem Pagamento', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco420', '06', '06', 'DOC Credito', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco420', '10', '10', 'Cheque Salario', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco422', '1', '1', 'On line', 1, 'P')
GO
INSERT INTO PSERVBANCO (CODCOLIGADA, CODTABELA, CODCLIENTE, CODINTERNO, DESCRICAO, PODEALTERAR, APLICACAO)
 VALUES (2, 'Bco422', '2', '2', 'Batch', 1, 'P')
GO

/* INSERINDO AS CONSTRAINTS */

ALTER TABLE GCONSIST ADD CONSTRAINT FKGCONSIST_GDINAM FOREIGN KEY (CODCOLIGADA, APLICACAO, CODTABELA) REFERENCES GDINAM(CODCOLIGADA, APLICACAO, CODIGO)
GO
ALTER TABLE GDEFCOMPL ADD CONSTRAINT FKGDEFCOMPL_GDINAM FOREIGN KEY (CODCOLTABDINAM, APLICTABDINAM, CODTABDINAM) REFERENCES GDINAM(CODCOLIGADA, APLICACAO, CODIGO)
GO
ALTER TABLE PBCOSERV ADD CONSTRAINT FKPBCOSERV_GDINAM FOREIGN KEY (CODCOLIGADA, APLICACAO, CODSERVICO) REFERENCES GDINAM(CODCOLIGADA, APLICACAO, CODIGO)
GO
ALTER TABLE PSERVBANCO ADD CONSTRAINT FKPSERVBANCO_GDINAM FOREIGN KEY (CODCOLIGADA, APLICACAO, CODTABELA) REFERENCES GDINAM(CODCOLIGADA, APLICACAO, CODIGO)
GO


/*##MAGNA##*/