/************************************************************/
/* CLIENTE:                  UNIFI                          */
/* BANCO DE DADOS:           MSSQL                          */
/* VERSÃO DO BANCO DE DADOS: 2000 - 54                      */
/* VERSÃO DA BASE DE DADOS:  4.02                           */
/* DATA DE CRIAÇÃO:          22/07/2002                     */
/* ANALISTA RESPONSÁVEL:     FUMIO                          */
/* OCORRÊNCIA RMAGILIS:                                     */
/* OBJETIVO:                 ALTERAR OS CÓDIGOS DAS FUNÇÕES */
/*                           QUE ESTÃO PREENCHIDAS COM      */ 
/*                           CÓDIGOS INTEIROS (1,2,3, etc)  */
/*                           PARA COLOCAR OS ZEROS NA FRENTE*/
/*                           PARA QUE FIQUE ORDENADO        */
/************************************************************/

DECLARE @CODCOLIGADA SMALLINT
DECLARE @CODIGO VARCHAR(10)
DECLARE @TAMANHO INT

DECLARE CURSOR_PFUNCAO CURSOR FOR
  SELECT CODCOLIGADA,CODIGO,LEN(CODIGO)
  FROM PFUNCAO
  WHERE CODCOLIGADA=1
OPEN CURSOR_PFUNCAO

FETCH NEXT FROM CURSOR_PFUNCAO
INTO @CODCOLIGADA,@CODIGO,@TAMANHO

WHILE @@FETCH_STATUS = 0
BEGIN
  IF @TAMANHO=1
  BEGIN  
    UPDATE PFUNCAO SET CODIGO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
    
    UPDATE EFUNCPROF SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PFHSTFCO SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PFSUBSTITUICAO SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PFUNC SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PTTOTFUNC SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VCHEFIA SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VFUNCAOEPI SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VFUNCAOPRETENDIDA SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VFUNCOESEXT SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VHABILIDADESFUNCAO SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VLOTACAO SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VPERFILEXAMELOT SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VPERFILFUNCAO SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VPLANOCARREIRA SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VRECRUTAMENTO SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VREQUISICAO SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VSELECOES SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VVALORFUNCAO SET CODFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VBIBRIGADISTA SET FUNCAOBRIGADA=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND FUNCAOBRIGADA=@CODIGO
    
    UPDATE VSELECOES SET CODFUNCPRETENDIDA=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCPRETENDIDA=@CODIGO
    
    UPDATE VPLANOCARREIRA SET CODPROXFUNCAO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODPROXFUNCAO=@CODIGO
    
    UPDATE VPLANOVAGASFUNCAO SET CODIGO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
    
    UPDATE VHISTVAGASFUNCAO SET CODIGO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
    
    UPDATE VFUNCAOHIST SET CODIGO=('000'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO 
  END  
  ELSE 
  IF @TAMANHO=2
  BEGIN
    UPDATE PFUNCAO SET CODIGO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
    
    UPDATE EFUNCPROF SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PFHSTFCO SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PFSUBSTITUICAO SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PFUNC SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PTTOTFUNC SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VCHEFIA SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VFUNCAOEPI SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VFUNCAOPRETENDIDA SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VFUNCOESEXT SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VHABILIDADESFUNCAO SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VLOTACAO SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VPERFILEXAMELOT SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VPERFILFUNCAO SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VPLANOCARREIRA SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VRECRUTAMENTO SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VREQUISICAO SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VSELECOES SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VVALORFUNCAO SET CODFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VBIBRIGADISTA SET FUNCAOBRIGADA=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND FUNCAOBRIGADA=@CODIGO
    
    UPDATE VSELECOES SET CODFUNCPRETENDIDA=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCPRETENDIDA=@CODIGO
    
    UPDATE VPLANOCARREIRA SET CODPROXFUNCAO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODPROXFUNCAO=@CODIGO
    
    UPDATE VPLANOVAGASFUNCAO SET CODIGO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
    
    UPDATE VHISTVAGASFUNCAO SET CODIGO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
    
    UPDATE VFUNCAOHIST SET CODIGO=('00'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO     
  END 
  ELSE 
  IF @TAMANHO=3
  BEGIN
    UPDATE PFUNCAO SET CODIGO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
    
    UPDATE EFUNCPROF SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PFHSTFCO SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PFSUBSTITUICAO SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PFUNC SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE PTTOTFUNC SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VCHEFIA SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VFUNCAOEPI SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VFUNCAOPRETENDIDA SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VFUNCOESEXT SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VHABILIDADESFUNCAO SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VLOTACAO SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VPERFILEXAMELOT SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VPERFILFUNCAO SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VPLANOCARREIRA SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VRECRUTAMENTO SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VREQUISICAO SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VSELECOES SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VVALORFUNCAO SET CODFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCAO=@CODIGO
    
    UPDATE VBIBRIGADISTA SET FUNCAOBRIGADA=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND FUNCAOBRIGADA=@CODIGO
    
    UPDATE VSELECOES SET CODFUNCPRETENDIDA=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODFUNCPRETENDIDA=@CODIGO
    
    UPDATE VPLANOCARREIRA SET CODPROXFUNCAO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODPROXFUNCAO=@CODIGO
    
    UPDATE VPLANOVAGASFUNCAO SET CODIGO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
    
    UPDATE VHISTVAGASFUNCAO SET CODIGO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
    
    UPDATE VFUNCAOHIST SET CODIGO=('0'+@CODIGO) WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO
  END
  ELSE
    UPDATE PFUNCAO SET CODIGO=@CODIGO WHERE CODCOLIGADA=@CODCOLIGADA AND CODIGO=@CODIGO

  FETCH NEXT FROM CURSOR_PFUNCAO
  INTO @CODCOLIGADA,@CODIGO,@TAMANHO
END

CLOSE CURSOR_PFUNCAO
DEALLOCATE CURSOR_PFUNCAO





/****************************************************************/
/* EXEMPLO PARA PRINTAR OS CÓDIGOS DE FUNÇÕES ANTES DA ALTERAÇÃO*/
/****************************************************************/
/*

DECLARE @CODCOLIGADA SMALLINT
DECLARE @CODIGO VARCHAR(10)
DECLARE @TAMANHO INT

DECLARE CURSOR_FUNCAO CURSOR FOR
  SELECT CODCOLIGADA,CODIGO,LEN(CODIGO)
  FROM PFUNCAO
  WHERE CODCOLIGADA=1
OPEN CURSOR_FUNCAO

FETCH NEXT FROM CURSOR_FUNCAO
INTO @CODCOLIGADA,@CODIGO,@TAMANHO

WHILE @@FETCH_STATUS = 0
BEGIN
  IF @TAMANHO=1
    PRINT ('000'+@CODIGO)
  ELSE IF @TAMANHO=2
    PRINT('00'+@CODIGO)
  ELSE IF @TAMANHO=3
    PRINT('0'+@CODIGO)
  ELSE
    PRINT(@CODIGO)

  FETCH NEXT FROM CURSOR_FUNCAO
  INTO @CODCOLIGADA,@CODIGO,@TAMANHO
END

CLOSE CURSOR_FUNCAO
DEALLOCATE CURSOR_FUNCAO
GO
*/


/*##MAGNA##*/